package:
  name: amazon-sagemaker-jupyter-ai-q-developer
  version: 0.1.0

source:
  url: https://files.pythonhosted.org/packages/89/9b/d4cfe1eefffc5c3ef13b459fda055a1d320bd55e2b28fe966bfd1a374315/amazon_sagemaker_jupyter_ai_q_developer-0.1.0.tar.gz
  sha256: c1fd9e6df632f59f3b357df123f4f4206868350acdeec62f064ab31dcc924a15

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - { { compiler('c') } }
    - python
    - pip
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - amazon_sagemaker_jupyter_ai_q_developer

about:
  home: https://aws.amazon.com/sagemaker/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A Python library for Amazon SageMaker Jupyter AI Q Developer.
  description: |
    A Python library for Amazon SageMaker Jupyter AI Q Developer
  dev_url: https://aws.amazon.com/sagemaker/
  doc_url: https://aws.amazon.com/sagemaker/
